Work and About me Section (Portfolio skeleton)
mrparkersson/mobile-version pull request #1
Opened 2021-11-25 14:09 UTC by mrparkersson

Pull request
Amo Parker Prince

What does this PR do?

This PR is the continuation of skeleton of a portfolio page. (mobile version)

Description of the task to be completed
Designing "Work" and "About me" Section"

Added the  section, ul, li, tags in HTML file
Used CSS file to style up the tags in HTML file
created test.MD files that have been ignored
How should it be tested

clone the repository
git clone https://github.com/mrparkersson/mobile-version.git
navigate to the folder
cd portfolio-skeleton
checkout the feature
feature-create-my-page

2021-11-25 15:34 UTC, mmsesay requested changes
Hi @mrparkersson , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-25 15:34 UTC, mmsesay commented on README.md
- [ ] It's really good you added the readme to your project. It will be nicer if we could please expand on the readme by following the [Microverse Readme Template](https://github.com/microverseinc/readme-template).

2021-11-25 15:34 UTC, mmsesay commented on index.html
> -    <header>Work and About section of portfolio mobile skelton</header>
- [ ] [OPTIONAL] Your header is missing out on the logo and the nav for the hamburger icon. Please try to include them.
- [ ] [OPTIONAL] Secondly, I believe you worked on the headline section of your project. That section is currently not available in this project. Can you please add it just after the header?

2021-11-25 15:34 UTC, mmsesay commented on index.css
> +}
- [ ] I believe this class is responsible for your paragraph. Currently, it is not using the correct font and font size. Let's try to add them here.

2021-11-25 15:34 UTC, mmsesay commented on index.html
> +      </nav>
- [ ] Well done in aligning out these technologies. Since these are a list of technologies, I suggest we wrap them inside a `ul` instead of a `nav`. And also place each `button` inside a `li`

See example:
``` 
<ul>
  <li> // your button goes  here </li>
</ul>
```

2021-11-25 15:34 UTC, mmsesay commented on index.html
> +        <button class="lgbtn" type="submit">See Project</button>
- [ ] [OPTIONAL] I think you can add the cursor pointer property to this button so that users will know that the button is clickable.

2021-11-25 15:34 UTC, mmsesay commented on index.html
> +      </div>
- [ ] By the look of things, you only added just a single project. Let's try to add the remaining as per the Figma design.

2021-11-25 15:34 UTC, mmsesay commented on index.html
> +        <button class="myresume" type="submit">Get My Resume</button>
- [ ] [OPTIONAL] I think you can add the cursor pointer property to this button so that users will know that the button is clickable.

2021-11-25 15:34 UTC, mmsesay commented on index.html
> +      <h2 class="recent margin">My Recent Works</h2>
- [ ] The title is currently aligned to the left. We can try center it to match the Figma design.

2021-11-25 15:34 UTC, mmsesay commented on index.html
> +        </div>
- [ ] As suggested above, please try to group these buttons inside a `ul` and a `li` for each button.

2021-11-25 18:53 UTC, enaburekhan requested changes
Hi Mmsesay, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Code review by **Eric Enaburekhan**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-11-25 18:53 UTC, enaburekhan commented on index.css
> +  font-size: 16px;
- [ ] Good job including the font-size. However, the last reviewer suggested using the correct font-size which includes adding the `line-height` so we can achieve what's in the design. Currently, we are still yet to meet the design specifications.
the design:
![image](https://user-images.githubusercontent.com/51296741/143486046-7b260a9a-57ca-4eb7-bbc1-dd761e3b6bf7.png)

Your project:
![image](https://user-images.githubusercontent.com/51296741/143486496-cd797a3b-ae82-446c-9174-cbec7778ac7f.png)

2021-11-25 18:53 UTC, enaburekhan commented on index.css
> +  border: none;
- [ ] Good job following the design in the `about-me` section. But we still need to add some few touches to make it look exactly like the design. According to the project requirements: You must stick to the design as much as possible (e.g., font, colors, images, tests, margins) using the templates in Figma. 

The design:
![image](https://user-images.githubusercontent.com/51296741/143489315-d4c1a1f0-1628-4a64-891c-cf2308fd549e.png)

Your design:
![image](https://user-images.githubusercontent.com/51296741/143489423-a7c660fa-8d04-4e39-aadf-4ca78bfc27db.png)

- I will suggest you check the font-size if they match what's in the design. Also, check color. Some have line-height properties in the design. Kindly check and add them to yours. Kindly consider this suggestions for the whole of the `about section`

2021-11-25 19:57 UTC, mrparkersson commented on README.md
> +Project Name
Bro that’s the same template I used. So which template again? Because with this your review I don’t think my README file must be tackled. Check again. Because you’re making my work tedious

2021-11-25 20:14 UTC, enaburekhan commented on README.md
> +Project Name
Hello Mrparkersson,
Ok, It looks quite different until I took a detailed look.

-  The only change currently in the template is the project title. I will suggest you also add a brief description of what the project is all about. 

- And the `Getting started` section,  highlighting how to run the project locally.

2021-11-25 21:11 UTC, mrparkersson commented on README.md
> +Project Name
I would like you to check the final code before I ask for the last review

2021-11-26 09:13 UTC, lily-coder approved these changes
Hi @mrparkersson , 

Good work implementing the changes as requested by the previous reviewers. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![image](https://user-images.githubusercontent.com/63964646/143556187-479139f2-407f-4dfc-a598-61192ab4f191.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-26 15:12 UTC, merged