Popup Window
mrparkersson/mobile-version pull request #10
Opened 2021-12-15 10:24 UTC by mrparkersson

Pull request
Amo Parker Prince

What does this PR do?

Add event listeners to buttons and elements to show a popup

Description of the task to be completed
Adding clicks in Javascript file

Add event listeners to close the menu and open it

clone the repository
git clone https://github.com/mrparkersson/mobile-version.git
navigate to the folder
cd portfolio-skeleton
checkout the feature
javascript-create-my-page

2021-12-15 17:45 UTC, alonsofl requested changes
Hi @team,

You have done a great job so far! :muscle:
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media2.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif)

## Required Changes ♻️
_Check the comments under the review._

## To highlight :dart:
- The popup window is working as expected :heavy_check_mark:
- Linters are working correctly :heavy_check_mark:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-15 17:45 UTC, alonsofl commented on index.html
> +        </button>
- [ ] You have done a good job with the popup :100: but there is an issue with this button because this is the only button that does not open the popup. Please, kindly fix this issue for a better user experience :smiley: :raised_hands:

2021-12-15 17:45 UTC, alonsofl commented on index.css
>    margin: 0;
- [ ] [OPTIONAL] I would suggest adding the property `cursor: pointer` to the (X) icon in the popup window because it could be helpful with the user experience if the cursor change and the user is aware that it is a clickable element :pushpin: :wink:

2021-12-16 01:21 UTC, carlos-ssh approved these changes
# 🍾🍾 **STATUS APPROVED** 👏🏽👏🏽

Hi @mrparkersson, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



![Approved](https://user-images.githubusercontent.com/22258274/138466108-6b14c541-6a88-44c5-ba76-c64992ac1835.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-16 16:29 UTC, merged